//
//  AddUserModelsModels.swift
//  FortniteStats
//
//  Created by Jair Pinedo on 3/21/19.
//  Copyright (c) 2019 Jair Pinedo. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum AddUser {
    
    enum ShowLoading {
        
        struct Response {
            var isLoading: Bool
        }
        
        struct ViewModel {
            var isLoading: Bool
        }
    }
    
    enum Add {
        
        struct Request {
            var username: String?
            var platform: String
        }
        
        struct Response {
        }
        
        struct ViewModel {
        }
    }
    
    enum ShowErrors {
        
        struct Response {
            let text: String
        }
        
        struct ViewModel {
            let text: String
        }
        
    }
    
}
