//
//  AddUserWorker.swift
//  FortniteStats
//
//  Created by Jair Pinedo on 3/25/19.
//  Copyright (c) 2019 Jair Pinedo. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import Alamofire

class AddUserWorker {
    
    typealias searchUserHandler = (Result<UserModel, HttpErrors>) -> Void
    
    func searchUserInServer(username: String, platform: String, completionHandler: @escaping searchUserHandler) {
        let url = "/\(platform)/\(username)"
        HttpRequest().request(path: url, method: .get, completionHandler: completionHandler)
    }

} 
