//
//  AddUserPresenter.swift
//  FortniteStats
//
//  Created by Jair Pinedo on 3/25/19.
//  Copyright (c) 2019 Jair Pinedo. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol AddUserPresentationLogic {
    func presentLoading(response: AddUser.ShowLoading.Response)
    func presentErrors(response: AddUser.ShowErrors.Response)
    func presentSuccesUser(response: AddUser.Add.Response)
}

class AddUserPresenter: AddUserPresentationLogic {
    
    weak var viewController: AddUserDisplayLogic?
    
    func presentLoading(response: AddUser.ShowLoading.Response) {
        let viewModel = AddUser.ShowLoading.ViewModel(isLoading: response.isLoading)
        viewController?.displayLoading(viewModel: viewModel)
    }
    
    func presentErrors(response: AddUser.ShowErrors.Response) {
        let viewModel = AddUser.ShowErrors.ViewModel(text: response.text)
        viewController?.presentErrors(viewModel: viewModel)
    }
    
    func presentSuccesUser(response: AddUser.Add.Response) {
        let viewModel = AddUser.Add.ViewModel()
        viewController?.presentSuccesUser(viewModel: viewModel)
    }
    
}
