//
//  AddUserInteractor.swift
//  FortniteStats
//
//  Created by Jair Pinedo on 3/21/19.
//  Copyright (c) 2019 Jair Pinedo. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol AddUserBusinessLogic {
    func addUser(request: AddUser.Add.Request)
}

protocol AddUserDataStore {
    var user: UserModel? { get set }
}

class AddUserInteractor: AddUserBusinessLogic, AddUserDataStore {
    
    var presenter: AddUserPresentationLogic?
    var worker: AddUserWorker = AddUserWorker()
    var user: UserModel?
    
    func addUser(request: AddUser.Add.Request) {
        
        let platform = request.platform
        guard let username = request.username, !username.isEmpty else {
            let message = "Username is invalid"
            
            let response = AddUser.ShowErrors.Response(text: message)
            presenter?.presentErrors(response: response)
            
            return
        }
        
        let response = AddUser.ShowLoading.Response(isLoading: true)
        presenter?.presentLoading(response: response)
        
        worker.searchUserInServer(username: username, platform: platform) { (result) in
            
            switch result {
            case .success(let user):
                self.user = user
                let response = AddUser.Add.Response()
                self.presenter?.presentSuccesUser(response: response)
            case .failure(let error):
                let resp = AddUser.ShowErrors.Response(text: error.getErrorMessage())
                self.presenter?.presentErrors(response: resp)
            }
            
        }
        
    }
    
}
