//
//  AddUserRouter.swift
//  FortniteStats
//
//  Created by Jair Pinedo on 3/25/19.
//  Copyright (c) 2019 Jair Pinedo. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol AddUserRoutingLogic {
    func routeToHome()
}

protocol AddUserDataPassing {
    var dataStore: AddUserDataStore? { get }
}

class AddUserRouter: NSObject, AddUserRoutingLogic, AddUserDataPassing {
    weak var viewController: AddUserViewController?
    var dataStore: AddUserDataStore?
    
    // MARK: - Routing
    
    func routeToHome() {
        let storyboard = UIStoryboard(name: "Home", bundle: .none)
        let destinationVC = storyboard.instantiateInitialViewController() as! HomeTabViewController
        navigateToHome(source: viewController!, destination: destinationVC)
    }
    
    // MARK: - Navigation
    
    func navigateToHome(source: AddUserViewController, destination: HomeTabViewController) {
        source.show(destination, sender: .none)
    }

}
