//
//  HomeTabInteractor.swift
//  FortniteStats
//
//  Created by Jair Pinedo on 5/9/19.
//  Copyright (c) 2019 Jair Pinedo. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol HomeTabBusinessLogic {
    func doSomething(request: HomeTab.Something.Request)
}

protocol HomeTabDataStore {
    //var name: String { get set }
}

class HomeTabInteractor: HomeTabBusinessLogic, HomeTabDataStore {
    var presenter: HomeTabPresentationLogic?
    var worker: HomeTabWorker?
    //var name: String = ""
    
    // MARK: Do something
    
    func doSomething(request: HomeTab.Something.Request) {
        worker = HomeTabWorker()
        worker?.doSomeWork()
        
        let response = HomeTab.Something.Response()
        presenter?.presentSomething(response: response)
    }
}
