//
//  HomeTabWorker.swift
//  FortniteStats
//
//  Created by Jair Pinedo on 5/9/19.
//  Copyright (c) 2019 Jair Pinedo. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class HomeTabWorker {
    func doSomeWork() {
    }
}
